### ISSUE TITLE
Call is broken?

### ISSUE THREAD

**Issue by oliversturm** [heowc/action-hexo#2]
I tried your action for my deployment, using the sample YAML code from the README. However, when the action is executed, the `hexo` command doesn't understand its sub-command. I see this output in the log (for the `clean` step, the other steps show the same with different sub-commands).

```
Run heowc/action-hexo@master
/usr/bin/docker run --name <some very long hex number> --label <a shorter hex number> --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/<myreponame>/<myreponame again>":"/github/workspace" <long hex number> clean
Usage: hexo <command>

Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
```

I wonder if a `--` ahead of the `clean` command would make a difference?

**Comment by heowc** [comment]
Hi, thanks for using my github actions.

Hmm ... The sample I wrote in the README shows only the action I created. If I'm right, it seems to be because I didn't do checkout separately.

The method I use is to run [checkout](https://github.com/actions/checkout) and [npm install](https://github.com/actions/setup-node) before using this.

**Comment by heowc** [comment]
@oliversturm Is the issue still reappearing?
If so, please let me know! thank you. :smile:

**Comment by oliversturm** [comment]
@heowc Sorry, I am working on something else right now. I will attempt to extend my configuration with these steps - I assumed that your sample did it all, which was probably stupid of me - but I haven't used GitHub Actions before so I guess my brain subconsciously thought there was magic involved :)

Meanwhile, on the surface I'm not convinced by the explanation - the error I receive looks like something I'd get for an invalid command, not like hexo is saying "I can't find a hexo site here". Perhaps I'm wrong.

I will get back to this, but it may be another few days. If you don't want the issue open, feel free to close it and I'll open a new one if and when necessary. Thanks for your help!

**Comment by heowc** [comment]
Any questions are welcome :)

I don't know exactly what problem I'm facing, but I need to reinforce the documentation.

I will correct the document in a short time. Thank you.

**Comment by oliversturm** [comment]
I have tested things again now, and you were right - the missing checkout was the problem. The action does what it should now. I'm confused about the error I received, but that's not important :)

I have a different problem, but I'll open a new issue for that. Thanks for your help!
